version "4.14.2"

#include "ZScript/math.zsc"
// PBWP_Core
#include "zscript/PBWP_Core/BeefHandler.zs"
#include "zscript/PBWP_Core/BeefCore.zs"
#include "zscript/PBWP_Core/BeefJMod.zs"
#include "zscript/PBWP_Core/BeefMelee.zs"
#include "zscript/PBWP_Core/AllWeaponSpawner.zc"
#include "zscript/PBWP_Core/PBWP_Projectiles.zs"
#include "zscript/PBWP_Core/BeefMonsterSpawnerA.zs"
#include "zscript/PBWP_Core/BeefMonsterSpawnerB.zs"


// PBWP_Systems
#include "zscript/PBWP_Systems/Magnets/Magnets.zs"
// KillStreak// 
#include "zscript/PBWP_Systems/Killstreak/KSHandler.zc"
#include "zscript/PBWP_Systems/Killstreak/KillStreak.zc"
#include "zscript/PBWP_Systems/Killstreak/PBWPHUDMessage.zs"
// Random Weapon Switch
#include "zscript/PBWP_Systems/Random Weapon Switcher/ZRWSwitchMenu.zc"
#include "zscript/PBWP_Systems/Random Weapon Switcher/ZRWSwitcher.zc"
// Doorbuster
#include "zscript/PBWP_Systems/Doorbuster/doorbuster.zs"
#include "zscript/PBWP_Systems/Doorbuster/doorbuster_handler.zs"

// PBWP_Misc
#include "zscript/PBWP_Misc/GORENEST.zs"
// ElementalismBoss
#include "zscript/PBWP_Misc/BEHOLD_BOSSES/E1_Export_1.zs"
// Player Pawn Insanity Beef: Will this be added later?
//#include "zscript/CustomPlayerClass/INPlayer.zc"
//#include "ZScript/CustomPlayerClass/PBMeleePlayer.zc"
// Spawners ZScript
#include "zscript/Insanity's Nightmare/ChainsawSpawn.zc"
#include "zscript/Weapons/Slot-3/CSSG/CSSGEvent.zs"
// Weapon Wheel Stuff
#include "zscript/Weapons/Slot-3/CSSG/CSSG_Wheel.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExt_Wheel.zs"
#include "zscript/Insanity's Nightmare/IN_SpecialWheeltest.zs"
#include "Zscript/PBWP_Misc/Individual_WeaponWheels/D2016Shotgun_Wheel.zs" 
#include "Zscript/PBWP_Misc/Individual_WeaponWheels/ASG_Wheel.zs"
// Casings
#include "zscript/Weapons/Slot-3/CSSG/Casings.zs"
#include "zscript/Insanity's Nightmare/HASGCasings.zc"
#include "zscript/Insanity's Nightmare/IN_BulletSystem.zc"
#include "zscript/Insanity's Nightmare/IN_SpecialProjectile.zc"
#include "zscript/Insanity's Nightmare/PlasmaRifleAssaultProjectile.zc"

// Weapons & Etc (Testing)

	// CSSG Stuff Begin
#include "zscript/Weapons/Slot-3/CSSG/CSSG.zs"
#include "zscript/Weapons/Slot-3/CSSG/CSSG_Upgrades.zs"
	// CSSG Stuff End
#include "ZScript/Weapons/Slot-4/HeavySniperRifle.zs"
#include "ZScript/Weapons/Slot-6/Excavator.zs"
#include "zscript/Weapons/Slot-8/LoRCalamityBlade.zs"
	// Demonic Exterminator Stuff Begin
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExt.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtFunctions.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtAttacks.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj2.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtProj3.zs"
#include "zscript/Weapons/Slot-0/DemonicExterminator/DemonicExtStuff.zs"
	// Demonic Exterminator Stuff End