#library "SpawnerScripts"
#include "zcommon.acs"

int GiveTID = -2147483648;
int GiveID = -2147483648;

Function int NextTID (void)
{
    for ( ; GiveTID < 0; GiveTID++)
    {
        If (!ThingCount (T_NONE, GiveTID))
            return GiveTID;
    }
    return 0;
}
Script "SetUserTID" (void)
{
	SetUserVariable(0, "user_tid", NextTID ());
	SetResultValue(NextTID());
	terminate;
}

Script "Live_Check" (int tid)
{
	int v = 0;
	If(GetActorProperty(tid, APROP_HEALTH) > 0)
		v++;
	SetResultValue(v);
}

Script "Get_Spawner_Status" (int arg1)
{
	int X = GetActorX(arg1);
	int Y = GetActorY(arg1);
	int Z = GetActorZ(arg1);
	SetActorPosition(0, X, Y, Z, 0);
}
