#include "zscript/Weapons/BaseWeapon_EquipmentAnims.zs"

// DETONATOR
class RemoteChargeDetonator : Inventory {Default{Inventory.MaxAmount 1;}}
class DetonatorAmmo : ammo
{
	Default
	{
		Inventory.Amount 1;
		Inventory.MaxAmount 1;
		Ammo.BackPackAmount 1;
		Ammo.BackPackMaxAmount 1;
		Inventory.PickUpMessage "";
		Inventory.Icon "REMTS0";
		+INVENTORY.IGNORESKILL;
		Scale 0.45;
	}
}

class QuickDetonator : Inventory {}
class TossGrenade : Inventory {}
class AlreadyThrownShieldSaw : Inventory {Default{Inventory.MaxAmount 1;}} // For the ShieldSaw BugFix

class PB_RevLauncherFireCount : Inventory{Default{Inventory.MaxAmount 3;}}
extend class PB_WeaponBase
{
	States
	{
		UseEquipment:
			TNT1 A 0 A_JumpIfInventory("CantDoAction", 1, "FailOverlay");
			TNT1 A 0 A_JumpIf(health <= 0, "FailOverlay");
			TNT1 A 0 {
				A_ClearOverlays(-80, -11);
				A_ClearOverlays(-9, 80);
				// The legs were -10
				A_GunFlash("Null"); //Fixes the Minigun heat overlay oversight
				A_TakeInventory("Zoomed", 1);
				A_TakeInventory("RailgunInfrared", 1);
				A_Zoomfactor(1.0);
				A_GiveInventory("KeepLaserDeactivated",1);
				A_StopSound(CHAN_WEAPON);
				A_StopSound(CHAN_VOICE);
				A_StopSound(CHAN_6);
				A_StopSound(CHAN_7);
				A_TakeInventory("UseEquipment", 1);
				A_GiveInventory("KeepLaserDeactivated",1);
			}
			TNT1 A 0 A_JumpIfInventory ("QuickDetonator", 1, "Detonator");
			TNT1 A 0 A_JumpIfInventory ("GrabbedBarrel", 1, "IdleBarrel");
			TNT1 A 0 A_JumpIfInventory ("GrabbedFlameBarrel", 1, "IdleFlameBarrel");
			TNT1 A 0 A_JumpIfInventory ("GrabbedIceBarrel", 1, "IdleIceBarrel");
			TNT1 A 0 A_JumpIfInventory("FragGrenadeSelected", 1, "ThrowGrenade");
			TNT1 A 0 A_JumpIfInventory("ProximityMineSelected", 1, "ThrowMine");
			TNT1 A 0 A_JumpIfInventory("ElecPodSelected", 1, "ThrowElecPod");
			TNT1 A 0 A_JumpIfInventory("StunGrenadeSelected", 1, "ThrowStun");
			TNT1 A 0 A_JumpIfInventory("LeechSelected", 1, "ThrowLeech");
			TNT1 A 0 A_JumpIfInventory("ShieldSelected", 1, "ThrowShieldGrenade");
			TNT1 A 0 A_JumpIfInventory("VoidGrenadeSelected", 1, "ThrowVoidGrenade");
			TNT1 A 0 A_JumpIfInventory("SwarmerSelected", 1, "ThrowSwarmer");
			TNT1 A 0 A_JumpIfInventory("LaserChargeSelected", 1, "ThrowLaserCharge");
			TNT1 A 0 A_JumpIfInventory("AcidChargeSelected", 1, "ThrowAcidCharge");
			TNT1 A 0 A_JumpIfInventory("AxeSelected", 1, "ThrowAxe");
			TNT1 A 0 A_JumpIfInventory("HookSelected", 1, "ThrowHook");
			TNT1 A 0 A_JumpIfInventory("ShieldSawSelected", 1, "ThrowShieldSaw");
			TNT1 A 0 A_JumpIfInventory("ShurikenSelected", 1, "ThrowShuriken");
			TNT1 A 0 A_JumpIfInventory("CaltropsSelected", 1, "ThrowCaltrops");
			TNT1 A 0 A_JumpIfInventory("BeaconSelected", 1, "ThrowBeacon");
			TNT1 A 0 A_JumpIfInventory("FreezebotSelected", 1, "ThrowFreezebot");
			//TNT1 A 0 A_JumpIfInventory("RevGunSelected", 1, "FireRevGun");
			//More stuff to come.....
			Goto GoingToReady;
		WheelCancelEquipment:
			TNT1 A 0
				{
				A_SetInventory("WW_ProximityMineSelected",0);
				A_SetInventory("WW_ElecPodSelected",0);
				A_SetInventory("WW_StunGrenadeSelected",0);
				A_SetInventory("WW_LeechSelected",0);
				A_SetInventory("WW_FragGrenadeSelected",0);
				A_SetInventory("WW_RevGunSelected",0);
				A_SetInventory("WW_ShieldSelected",0);
				A_SetInventory("WW_VoidGrenadeSelected",0);
				A_SetInventory("WW_SwarmerSelected",0);
				A_SetInventory("WW_LaserChargeSelected",0);
				A_SetInventory("WW_AcidChargeSelected",0);
				A_SetInventory("WW_AxeSelected",0);
				A_SetInventory("WW_HookSelected",0);
				A_SetInventory("WW_ShieldSawSelected",0);
				A_SetInventory("WW_ShurikenSelected",0);
				A_SetInventory("WW_CaltropsSelected",0);
				A_SetInventory("WW_BeaconSelected",0);
				A_SetInventory("WW_FreezebotSelected",0);
				A_SetInventory("CantWeaponSpecial",0);
				}
			goto Equipment_Toggle_Handler_Overlay;
		SwitchEquipment:	
			TNT1 A 0 A_TakeInventory("ToggleEquipment", 1);
			TNT1 A 0 {
				if(CountInv("WW_ProximityMineSelected") && CountInv("ProximityMineSelected") >=1)
					{A_Print("Equipment already selected: Proximity Mine"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_ElecPodSelected") && CountInv("ElecPodSelected") >=1)
					{A_Print("Equipment already selected: Electric Pod"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_StunGrenadeSelected") && CountInv("StunGrenadeSelected") >=1)
					{A_Print("Equipment already selected: Stun Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_LeechSelected") && CountInv("LeechSelected") >=1)
					{A_Print("Equipment already selected: Leech"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_FragGrenadeSelected") && CountInv("FragGrenadeSelected") >=1)
					{A_Print("Equipment already selected: Frag Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_RevGunSelected") && CountInv("RevGunSelected") >=1)
					{A_Print("Equipment already selected: Revenant Launcher"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_ShieldSelected") && CountInv("ShieldSelected") >=1)
					{A_Print("Equipment already selected: Shield Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_VoidGrenadeSelected") && CountInv("VoidGrenadeSelected") >=1)
					{A_Print("Equipment already selected: Void Grenade"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_SwarmerSelected") && CountInv("SwarmerSelected") >=1)
					{A_Print("Equipment already selected: Swarm Pod"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_LaserChargeSelected") && CountInv("LaserChargeSelected") >=1)
					{A_Print("Equipment already selected: Laser Charge"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_AcidChargeSelected") && CountInv("AcidChargeSelected") >=1)
					{A_Print("Equipment already selected: Acid Charge"); return ResolveState("WheelCancelEquipment");}	
				if(CountInv("WW_AxeSelected") && CountInv("AxeSelected") >=1)
					{A_Print("Equipment already selected: Axe"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_HookSelected") && CountInv("HookSelected") >=1)
					{A_Print("Equipment already selected: Meat Hook"); return ResolveState("WheelCancelEquipment");}	
				if(CountInv("WW_ShieldSawSelected") && CountInv("ShieldSawSelected") >=1)
					{A_Print("Equipment already selected: Shield Saw"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_ShurikenSelected") && CountInv("ShurikenSelected") >=1)
					{A_Print("Equipment already selected: Explosive Hands"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_CaltropsSelected") && CountInv("CaltropsSelected") >=1)
					{A_Print("Equipment already selected: Clatrops"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_BeaconSelected") && CountInv("BeaconSelected") >=1)
					{A_Print("Equipment already selected: Beacon"); return ResolveState("WheelCancelEquipment");}
				if(CountInv("WW_FreezebotSelected") && CountInv("FreezebotSelected") >=1)
					{A_Print("Equipment already selected: Freeze Bot"); return ResolveState("WheelCancelEquipment");}

				//Ammo Checks
				if(CountInv("WW_ProximityMineSelected") >=1)
					{
					if(CountInv("PB_ProxMineAmmo") <=0)
						{A_Print("No Mines Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_ElecPodSelected") >=1)
					{
					if(CountInv("ElecPodAmmo") <=0)
						{A_Print("No Electric Pod Available"); return ResolveState("WheelCancelEquipment");}
					}	
				if(CountInv("WW_StunGrenadeSelected") >=1)
					{
					if(CountInv("PB_StunGrenadeAmmo") <=0)
						{A_Print("No Stun Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_LeechSelected") >=1)
					{
					if(CountInv("HasLeech") <=0)
						{A_Print("No Leech Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_RevGunSelected") >=1)
					{
					if(CountInv("PB_QuickLauncherAmmo") <=0)
						{A_Print("No Revenant Launcher Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_FragGrenadeSelected") >=1)
					{
					if(CountInv("PB_GrenadeAmmo") <=0)
						{A_Print("No Frag Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_ShieldSelected") >=1)
					{
					if(CountInv("ShieldGrenadeAmmo") <=0)
						{A_Print("No Shield Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_VoidGrenadeSelected") >=1)
					{
					if(CountInv("VoidGrenadeAmmo") <=0)
						{A_Print("No Void Grenades Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_AxeSelected") >=1)
					{
					if(CountInv("PB_Axe") <=0)
						{A_Print("No Axe Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_HookSelected") >=1)
					{
					if(CountInv("HookAmmo") <=0)
						{A_Print("You Don't Have the Meat Hook"); return ResolveState("WheelCancelEquipment");}
					}	
				if(CountInv("WW_ShieldSawSelected") >=1)
					{
					if(CountInv("ShieldSawAmmo") <=0)
						{A_Print("You Don't Have the Shield Saw"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_ShurikenSelected") >=1)
					{
					if(CountInv("ShurikenAmmo") <=0)
						{A_Print("No Shurikens Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_CaltropsSelected") >=1)
					{
					if(CountInv("CaltropsAmmo") <=0)
						{A_Print("No Caltrops Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_BeaconSelected") >=1)
					{
					if(CountInv("BeaconAmmo") <=0)
						{A_Print("No Beacon Available"); return ResolveState("WheelCancelEquipment");}
					}
				if(CountInv("WW_FreezebotSelected") >=1)
					{
					if(CountInv("FreezeBotAmmo") <=0)
						{A_Print("No Freeze Bot Available"); return ResolveState("WheelCancelEquipment");}
					}

				// End
				return ResolveState(null);
				}
			TNT1 A 0 
				{
					if(CountInv("WW_ProximityMineSelected") >=1)
						{ 
							A_Print("Equipment Selected: Proximity Mine"); 
							A_SetInventory("ProximityMineSelected",1);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_ElecPodSelected") >=1)
						{ 
							A_Print("Equipment Selected: Electric Pod"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",1);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_StunGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Stun Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",1);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_LeechSelected") >=1)
						{ 
							A_Print("Equipment Selected: Leech"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",1);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_RevGunSelected") >=1)
						{ 
							A_Print("Equipment Selected: Revenant Launcher"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",1);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("REVUP", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_FragGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Frag Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",1);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_ShieldSelected") >=1)
						{ 
							A_Print("Equipment Selected: Shield Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",1);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}	
					if(CountInv("WW_VoidGrenadeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Void Grenade"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",1);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_SwarmerSelected") >=1)
						{ 
							A_Print("Equipment Selected: Swarm Pod / Detonator"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",1);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}				
					if(CountInv("WW_LaserChargeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Laser Charge / Detonator"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",1);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_AcidChargeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Acid Charge / Detonator"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",1);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}	
					if(CountInv("WW_AxeSelected") >=1)
						{ 
							A_Print("Equipment Selected: Axe"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",1);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_HookSelected") >=1)
						{ 
							A_Print("Equipment Selected: Meat Hook"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",1);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_ShieldSawSelected") >=1)
						{ 
							A_Print("Equipment Selected: Shield Saw"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",1);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_ShurikenSelected") >=1)
						{ 
							A_Print("Equipment Selected: Shurikens"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",1);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}	
					if(CountInv("WW_CaltropsSelected") >=1)
						{ 
							A_Print("Equipment Selected: Shurikens"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",1);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
					if(CountInv("WW_BeaconSelected") >=1)
						{ 
							A_Print("Equipment Selected: Beacon"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",1);
							A_SetInventory("FreezebotSelected",0);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}		
					if(CountInv("WW_FreezebotSelected") >=1)
						{ 
							A_Print("Equipment Selected: Freeze Bot"); 
							A_SetInventory("ProximityMineSelected",0);
							A_SetInventory("ElecPodSelected",0);
							A_SetInventory("StunGrenadeSelected",0);
							A_SetInventory("LeechSelected",0);
							A_SetInventory("RevGunSelected",0);
							A_SetInventory("FragGrenadeSelected",0);
							A_SetInventory("ShieldSelected",0);
							A_SetInventory("VoidGrenadeSelected",0);
							A_SetInventory("SwarmerSelected",0);
							A_SetInventory("LaserChargeSelected",0);
							A_SetInventory("AcidChargeSelected",0);
							A_SetInventory("AxeSelected",0);
							A_SetInventory("HookSelected",0);
							A_SetInventory("ShieldSawSelected",0);
							A_SetInventory("ShurikenSelected",0);
							A_SetInventory("CaltropsSelected",0);
							A_SetInventory("BeaconSelected",0);
							A_SetInventory("FreezebotSelected",1);
							A_StartSound("GRNPIN", 3);
							return ResolveState("WheelCancelEquipment");
						}
						
					//End
				return ResolveState(null);
				}
			goto Equipment_Toggle_Handler_Overlay;
	}
}